version: '3.9'
services:
  application:
    container_name: ms-mail-gateway
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    hostname: ms-mail-gateway
    ports:
      - "3000:3000"
    restart: on-failure
    environment: 
      - TZ=America/Sao_Paulo
    networks:
      - hc-network-services
    volumes:
      - ./../logs:/usr/app/logs
volumes:
  application:
    external: true
networks:
  hc-network-services:
    external: true 
    